apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-task-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genesis-task-updater
  template:
    metadata:
      labels:
        app: genesis-task-updater
    spec:
      containers:
      - name: genesis-task-updater
        image: stevenge-godscode/genesis-task-updater:latest
