apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-script-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genesis-script-generator
  template:
    metadata:
      labels:
        app: genesis-script-generator
    spec:
      containers:
      - name: genesis-script-generator
        image: stevenge-godscode/genesis-script-generator:latest
