apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-retrieve-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genesis-retrieve-task
  template:
    metadata:
      labels:
        app: genesis-retrieve-task
    spec:
      containers:
      - name: genesis-retrieve-task
        image: stevenge-godscode/genesis-retrieve-task:latest
